services:
  openppp2:
    image: aspnmy/openppp2:alpine
    container_name: openppp2_client
    restart: always
    privileged: true  # USE_IO=true 需要添加特权模式
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./appsettings.json:/opt/appsettings.json
    network_mode: host
    environment:
    - USE_IO=true
    command: ppp --mode=client --tun-host=yes --tun-flash=yes --tun-ssmt=4/mq --tun-mux=8
